version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      aspnetcore:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.*"
        update-types:
          - "minor"
          - "patch"
      analyzers:
        patterns:
          - "SecurityCodeScan*"
          - "SonarAnalyzer*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/WebDevSecOps"
    schedule:
      interval: "weekly"
      day: "monday"
